/*
 * Quiz API
 *
 * This is a simple server for managing quiz questions
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using com.awawawiwa.DTOs;
using com.awawawiwa.Services;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System;
using System.Threading.Tasks;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("v1/users")]
    public class UserController : ControllerBase
    {
        private readonly IUserService _userService;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="userService"></param>
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        /// <summary>
        /// Login a user
        /// </summary>
        /// <param name="userInputDTO"></param>
        /// <response code="200">Login successful</response>
        /// <response code="401">Invalid username or password</response>
        [HttpPost("login")]
        [ValidateModelState]
        [SwaggerOperation("LoginUser")]
        [SwaggerResponse(200, "Login successful")]
        [SwaggerResponse(401, "Invalid username or password")]
        public virtual async Task<IActionResult> LoginUserAsync([FromBody] LoginUserInputDTO userInputDTO)
        {

            var loginUserOutputDTO = await _userService.LoginUserAsync(userInputDTO);

            if (string.IsNullOrEmpty(loginUserOutputDTO?.Token))
            {
                return Unauthorized(new { message = "Invalid username or password" });
            }

            return Ok(loginUserOutputDTO);
        }

        /// <summary>
        /// Create a new user
        /// </summary>
        /// <param name="body"></param>
        /// <response code="201">Successfully created new user</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="409">Db Conflict</response>
        [HttpPost]
        [ValidateModelState]
        [SwaggerOperation("CreateUser")]
        [SwaggerResponse(statusCode: 201, description: "Successfully created new user")]
        [SwaggerResponse(statusCode: 500, description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 409, description: "Db Conflict")]
        public virtual async Task<IActionResult> CreateUserAsync([FromBody] CreateUserInputDTO body)
        {
            var result = await _userService.CreateUserAsync(body);
            if (!result.Success)
            {
                return Conflict(new { message = result.ErrorMessage });
            }

            return Ok();
        }

        /// <summary>
        /// Delete User
        /// </summary>
        /// <param name="userId"></param>
        /// <response code="200">Successfully deleted user</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="404">User not found</response>
        [HttpDelete("{userId}")]
        [ValidateModelState]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [SwaggerOperation("DeleteUser")]
        [SwaggerResponse(statusCode: 200, description: "Successfully deleted user")]
        [SwaggerResponse(statusCode: 403, description: "Forbidden - can't delete other users")]
        [SwaggerResponse(statusCode: 500, description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 404, description: "User not found")]
        public virtual async Task<IActionResult> DeleteUserAsync(Guid userId)
        {
            var loggedInUser = User.FindFirst("userId")?.Value;

            if (string.IsNullOrEmpty(loggedInUser) || loggedInUser != userId.ToString())
            {
                return Forbid();
            }

            var token = Request.Headers["Authorization"].ToString().Replace("Bearer ", "");

            var result = await _userService.DeleteUserAsync(userId);
            if (!result.Success)
            {
                return NotFound(new { message = result.ErrorMessage });
            }

            _userService.LogoutUser(token);
            return Ok();
        }

        /// <summary>
        /// Logout user
        /// </summary>
        /// <response code="201">Successfully deleted user</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="404">User not found</response>
        [HttpPost("logout")]
        [ValidateModelState]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [SwaggerOperation("LogoutUser")]
        [SwaggerResponse(statusCode: 201, description: "Successfully logged out user")]
        [SwaggerResponse(statusCode: 403, description: "Forbidden - can't logout other users")]
        [SwaggerResponse(statusCode: 500, description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 404, description: "User not found")]
        public virtual IActionResult LogoutUserAsync()
        {
            var token = Request.Headers["Authorization"].ToString().Replace("Bearer ", "");

            if (string.IsNullOrEmpty(token))
            {
                return BadRequest("No token found");
            }

            _userService.LogoutUser(token);
            return Ok();
        }

        /// <summary>
        /// Logout user
        /// </summary>
        /// <response code="201">Successfully deleted user</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="404">User not found</response>
        [HttpPost("loginstatus")]
        [ValidateModelState]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [SwaggerOperation("LogoutUser")]
        [SwaggerResponse(statusCode: 201, description: "Successfully logged out user")]
        [SwaggerResponse(statusCode: 403, description: "Forbidden - can't logout other users")]
        [SwaggerResponse(statusCode: 500, description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 404, description: "User not found")]
        public virtual IActionResult IsUserLoggedIn()
        {
            var token = Request.Headers["Authorization"].ToString().Replace("Bearer ", "");

            if (string.IsNullOrEmpty(token))
            {
                return BadRequest("No token found");
            }

            var loginStatus = _userService.IsUserLoggedIn(token);
            return Ok(loginStatus);
        }

        /// <summary>
        /// Get user data
        /// </summary>
        /// <response code="201">Successfully deleted user</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="404">User not found</response>
        [HttpGet("me")]
        [ValidateModelState]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [SwaggerOperation("LogoutUser")]
        [SwaggerResponse(statusCode: 201, description: "Successfully logged out user")]
        [SwaggerResponse(statusCode: 403, description: "Forbidden - can't logout other users")]
        [SwaggerResponse(statusCode: 500, description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 404, description: "User not found")]
        public virtual async Task<IActionResult> GetUserDataAsync()
        {
            var userId = User.FindFirst("userId")?.Value;

            var userData = await _userService.GetUserDataAsync(Guid.Parse(userId));
            return Ok(userData);
        }
    }
}
